#!/usr/bin/env python3
"""Verify universal Euler cancellations without a Hermitian-symbol ansatz.

At each unoriented Fourier mode the symbol is a completely general complex
2-by-2 matrix, with the sole reality constraint R(-k) = conjugate(R(k)).
The eight real parameters are ordered as the real and imaginary parts of
R_11, R_12, R_21, R_22.  A seven-mode exact seed and unequal-length target
blocks show that the Hermitian classification misses no universal cubic
cancellations: the cancellation itself forces Hermiticity.
"""

from __future__ import annotations

from fractions import Fraction
from itertools import product
from typing import Dict, Iterable, List, Sequence

from explore_full_multiplier import (
    Gaussian,
    GVec,
    IMAGINARY_UNIT,
    ONE,
    ZERO,
    add_independent_row,
    coordinates,
    exact_triad_modes,
    gadd,
    gdot,
    gmul,
    invariant_row,
    orthogonal_frame,
)
from verify_full_multiplier_rigidity import (
    BOOLEAN_SEED_REPRESENTATIVES,
    PHASES,
    boolean_seed_vectors,
    nonzero_vectors,
)
from verify_laplacian_rigidity import (
    Vec,
    add,
    cross,
    neg,
    norm2,
    transverse_basis,
    unoriented,
)


SEED_PRIMES = (1_000_003, 1_000_000_007)

# A compact, explicit nonzero-minor certificate.  Row indices are zero-based
# in the deterministic sequence of nonzero seven-mode seed equations generated by
# analyze_seed(); columns use the eight-real-parameters-per-mode ordering in
# general_invariant_row().  Reducing this 54-by-54 minor modulo either prime
# gives the recorded nonzero determinant, which certifies rank at least 54
# over Q.  Energy and helicity certify the matching upper bound.
EXPECTED_SELECTED_INDICES = (
    0, 1, 8, 9, 16, 17, 24, 25, 32, 33, 40, 41, 64, 65, 72, 73, 80, 81,
    88, 89, 96, 97, 104, 105, 128, 129, 144, 145, 152, 153, 160, 161, 176,
    177, 184, 185, 256, 257, 264, 265, 272, 273, 288, 289, 296, 297, 304,
    305, 376, 377, 384, 385, 393, 400,
)
EXPECTED_PIVOT_COLUMNS = tuple(range(53)) + (55,)
EXPECTED_MINOR_DETERMINANTS = (190_194, 891_695_525)


def general_invariant_row(
    modes: Dict[Vec, GVec], representatives: Sequence[Vec]
) -> List[Fraction]:
    """Coefficients of <Rw,(w dot grad)w> for arbitrary complex R(k)."""
    index = {k: i for i, k in enumerate(representatives)}
    row: List[Gaussian] = [ZERO] * (8 * len(representatives))
    for p, q, r in product(modes, repeat=3):
        if add(add(p, q), r) != (0, 0, 0):
            continue
        representative = unoriented(p)
        base = 8 * index[representative]
        frame = orthogonal_frame(representative)
        x1, x2 = coordinates(modes[p], frame)
        derivative = gmul(IMAGINARY_UNIT, gdot(modes[q], r))
        nonlinear = tuple(gmul(derivative, component) for component in modes[r])
        y1, y2 = coordinates(nonlinear, frame)  # type: ignore[arg-type]
        orientation = 1 if p == representative else -1
        products = (
            gmul(y1, x1),
            gmul(y1, x2),
            gmul(y2, x1),
            gmul(y2, x2),
        )
        for matrix_index, coefficient in enumerate(products):
            real_column = base + 2 * matrix_index
            imaginary_column = real_column + 1
            row[real_column] = gadd(row[real_column], coefficient)
            imaginary_coefficient = gmul(IMAGINARY_UNIT, coefficient)
            if orientation < 0:
                imaginary_coefficient = (
                    -imaginary_coefficient[0],
                    -imaginary_coefficient[1],
                )
            row[imaginary_column] = gadd(
                row[imaginary_column], imaginary_coefficient
            )

    assert all(value[1] == 0 for value in row)
    return [value[0] for value in row]


def triad_rows(
    p: Vec, q: Vec, r: Vec, representatives: Sequence[Vec]
) -> Iterable[List[Fraction]]:
    for a, b, c in product(
        transverse_basis(p), transverse_basis(q), transverse_basis(r)
    ):
        for phase in PHASES:
            row = general_invariant_row(
                exact_triad_modes(p, q, r, a, b, c, phase), representatives
            )
            if any(row):
                yield row


def general_energy_vector(representatives: Sequence[Vec]) -> List[int]:
    """The identity operator in the eight-real-parameter coordinates."""
    result: List[int] = []
    for k in representatives:
        e1, e2 = orthogonal_frame(k)
        result.extend((norm2(e1), 0, 0, 0, 0, 0, norm2(e2), 0))
    return result


def general_helicity_vector(representatives: Sequence[Vec]) -> List[int]:
    """The curl symbol in the eight-real-parameter coordinates."""
    result: List[int] = []
    for k in representatives:
        e1, _e2 = orthogonal_frame(k)
        scale = norm2(k) * norm2(e1)
        result.extend((0, 0, 0, -scale, 0, scale, 0, 0))
    return result


def embed_hermitian_row(row: Sequence[Fraction]) -> List[Fraction]:
    """Restrict a general-symbol row to Hermitian symbol coordinates."""
    assert len(row) % 8 == 0
    result: List[Fraction] = []
    for start in range(0, len(row), 8):
        re11, _im11, re12, im12, re21, im21, re22, _im22 = row[start : start + 8]
        result.extend((re11, re22, re12 + re21, im12 - im21))
    return result


def add_independent_row_mod(
    basis: Dict[int, List[int]], source: Sequence[Fraction], prime: int
) -> bool:
    row = [
        value.numerator * pow(value.denominator, -1, prime) % prime
        for value in source
    ]
    for pivot in sorted(basis):
        if not row[pivot]:
            continue
        factor = row[pivot]
        row = [
            (entry - factor * basis[pivot][j]) % prime
            for j, entry in enumerate(row)
        ]
    pivot = next((j for j, entry in enumerate(row) if entry), None)
    if pivot is None:
        return False
    inverse = pow(row[pivot], -1, prime)
    basis[pivot] = [(entry * inverse) % prime for entry in row]
    return True


def determinant_mod(
    rows: Sequence[Sequence[Fraction]], columns: Sequence[int], prime: int
) -> int:
    """Determinant of the selected square rational minor over F_prime."""
    assert len(rows) == len(columns)
    matrix = [
        [
            row[column].numerator
            * pow(row[column].denominator, -1, prime)
            % prime
            for column in columns
        ]
        for row in rows
    ]
    determinant = 1
    size = len(matrix)
    for column in range(size):
        pivot = next(
            (row for row in range(column, size) if matrix[row][column]), None
        )
        assert pivot is not None
        if pivot != column:
            matrix[column], matrix[pivot] = matrix[pivot], matrix[column]
            determinant = -determinant
        pivot_value = matrix[column][column]
        determinant = determinant * pivot_value % prime
        inverse = pow(pivot_value, -1, prime)
        matrix[column] = [entry * inverse % prime for entry in matrix[column]]
        for row in range(column + 1, size):
            if not matrix[row][column]:
                continue
            factor = matrix[row][column]
            matrix[row] = [
                (entry - factor * matrix[column][j]) % prime
                for j, entry in enumerate(matrix[row])
            ]
    return determinant % prime


def analyze_seed() -> tuple[
    int,
    int,
    int,
    tuple[int, int],
    tuple[int, ...],
    tuple[int, ...],
    tuple[int, int],
]:
    vectors = boolean_seed_vectors()
    representatives = list(BOOLEAN_SEED_REPRESENTATIVES)
    basis: Dict[int, List[Fraction]] = {}
    primes = SEED_PRIMES
    modular_bases: tuple[Dict[int, List[int]], Dict[int, List[int]]] = ({}, {})
    energy = general_energy_vector(representatives)
    helicity = general_helicity_vector(representatives)
    equations = 0
    denominators: set[int] = set()
    selected_indices: List[int] = []
    selected_rows: List[List[Fraction]] = []
    for p in vectors:
        for q in vectors:
            r = neg(add(p, q))
            if r not in vectors or not (p <= q <= r) or cross(p, q) == (0, 0, 0):
                continue
            for row in triad_rows(p, q, r, representatives):
                equations += 1
                denominators.update(value.denominator for value in row)
                assert sum(x * y for x, y in zip(row, energy)) == 0
                assert sum(x * y for x, y in zip(row, helicity)) == 0
                if add_independent_row(basis, row):
                    selected_indices.append(equations - 1)
                    selected_rows.append(row)
                for modular_basis, prime in zip(modular_bases, primes):
                    add_independent_row_mod(modular_basis, row, prime)
    pivot_columns = tuple(sorted(basis))
    minor_determinants = tuple(
        determinant_mod(selected_rows, pivot_columns, prime) for prime in primes
    )
    assert all(minor_determinants)
    assert denominators == {1, 2, 3, 6}
    assert all(
        all(denominator % prime for denominator in denominators)
        for prime in primes
    )
    assert tuple(selected_indices) == EXPECTED_SELECTED_INDICES
    assert pivot_columns == EXPECTED_PIVOT_COLUMNS
    assert minor_determinants == EXPECTED_MINOR_DETERMINANTS
    return (
        len(basis),
        8 * len(representatives),
        equations,
        tuple(len(modular_basis) for modular_basis in modular_bases),  # type: ignore[return-value]
        tuple(selected_indices),
        pivot_columns,
        minor_determinants,  # type: ignore[return-value]
    )


def general_direct_target_rows(p: Vec, q: Vec, r: Vec) -> List[List[Fraction]]:
    """Return the eight target-symbol coefficients without parent blocks."""
    representative = unoriented(p)
    frame = orthogonal_frame(representative)
    orientation = 1 if p == representative else -1
    rows: List[List[Fraction]] = []
    phases = ((ONE, ONE, ONE), (IMAGINARY_UNIT, ONE, ONE))
    for a, b, c in product(
        transverse_basis(p), transverse_basis(q), transverse_basis(r)
    ):
        for phase in phases:
            modes = exact_triad_modes(p, q, r, a, b, c, phase)
            x1, x2 = coordinates(modes[p], frame)
            q_factor = gmul(IMAGINARY_UNIT, gdot(modes[q], r))
            r_factor = gmul(IMAGINARY_UNIT, gdot(modes[r], q))
            nonlinear = tuple(
                gadd(gmul(q_factor, modes[r][i]), gmul(r_factor, modes[q][i]))
                for i in range(3)
            )
            y1, y2 = coordinates(nonlinear, frame)
            products = (
                gmul(y1, x1),
                gmul(y1, x2),
                gmul(y2, x1),
                gmul(y2, x2),
            )
            row: List[Fraction] = []
            for coefficient in products:
                row.append(2 * coefficient[0])
                row.append(-2 * orientation * coefficient[1])
            if any(row):
                rows.append(row)
    return rows


def exact_rank(rows: Iterable[Sequence[Fraction]]) -> int:
    basis: Dict[int, List[Fraction]] = {}
    for row in rows:
        add_independent_row(basis, row)
    return len(basis)


def direct_evaluation(
    modes: Dict[Vec, GVec], representatives: Sequence[Vec], parameters: Sequence[int]
) -> Fraction:
    """Evaluate the full convolution after grouping by recipient mode.

    This is deliberately organized differently from ``general_invariant_row``
    and serves as an independent check of orientation and complex-matrix signs.
    """
    assert len(parameters) == 8 * len(representatives)
    index = {k: i for i, k in enumerate(representatives)}
    nonlinear: Dict[Vec, GVec] = {}
    for q, r in product(modes, repeat=2):
        target = add(q, r)
        derivative = gmul(IMAGINARY_UNIT, gdot(modes[q], r))
        term = tuple(gmul(derivative, component) for component in modes[r])
        old = nonlinear.get(target, (ZERO, ZERO, ZERO))
        nonlinear[target] = tuple(
            gadd(old[j], term[j]) for j in range(3)
        )  # type: ignore[assignment]

    total = ZERO
    for k, amplitude in modes.items():
        recipient = nonlinear.get(neg(k))
        if recipient is None:
            continue
        representative = unoriented(k)
        orientation = 1 if k == representative else -1
        start = 8 * index[representative]
        block = parameters[start : start + 8]
        matrix = (
            (
                (Fraction(block[0]), Fraction(orientation * block[1])),
                (Fraction(block[2]), Fraction(orientation * block[3])),
            ),
            (
                (Fraction(block[4]), Fraction(orientation * block[5])),
                (Fraction(block[6]), Fraction(orientation * block[7])),
            ),
        )
        x = coordinates(amplitude, orthogonal_frame(representative))
        y = coordinates(recipient, orthogonal_frame(representative))
        for i in range(2):
            for j in range(2):
                total = gadd(total, gmul(matrix[i][j], gmul(x[j], y[i])))
    assert total[1] == 0
    return total[0]


def check_hermitian_restriction() -> int:
    """Cross-check every general coefficient against the older verifier."""
    examples = (
        ((1, 0, 0), (0, 1, 0), (-1, -1, 0)),
        ((1, 1, 0), (0, 0, 1), (-1, -1, -1)),
        ((-2, -1, 0), (0, 1, 1), (2, 0, -1)),
    )
    checked = 0
    for p, q, r in examples:
        representatives = sorted({unoriented(p), unoriented(q), unoriented(r)})
        for a, b, c in product(
            transverse_basis(p), transverse_basis(q), transverse_basis(r)
        ):
            for phase in PHASES:
                modes = exact_triad_modes(p, q, r, a, b, c, phase)
                general_row = general_invariant_row(modes, representatives)
                hermitian_row = invariant_row(modes, representatives)
                assert embed_hermitian_row(general_row) == hermitian_row
                checked += 1
    return checked


def check_full_convolution() -> int:
    examples = (
        ((1, 0, 0), (0, 1, 0), (-1, -1, 0)),
        ((1, 1, 0), (0, 0, 1), (-1, -1, -1)),
        ((-2, -1, 0), (0, 1, 1), (2, 0, -1)),
    )
    checked = 0
    for example_index, (p, q, r) in enumerate(examples):
        representatives = sorted({unoriented(p), unoriented(q), unoriented(r)})
        parameters = [
            ((7 * j + 5 * example_index) % 19) - 9
            for j in range(8 * len(representatives))
        ]
        for a, b, c in product(
            transverse_basis(p), transverse_basis(q), transverse_basis(r)
        ):
            for phase in PHASES:
                modes = exact_triad_modes(p, q, r, a, b, c, phase)
                row = general_invariant_row(modes, representatives)
                row_value = sum(
                    coefficient * parameter
                    for coefficient, parameter in zip(row, parameters)
                )
                assert row_value == direct_evaluation(
                    modes, representatives, parameters
                )
                checked += 1
    return checked


def check_direct_target_formula() -> int:
    examples = (
        ((1, 0, 0), (0, 1, 0), (-1, -1, 0)),
        ((1, 1, 0), (0, 0, 1), (-1, -1, -1)),
        ((-2, -1, 0), (0, 1, 1), (2, 0, -1)),
    )
    comparisons = 0
    for p, q, r in examples:
        representatives = sorted({unoriented(p), unoriented(q), unoriented(r)})
        start = 8 * representatives.index(unoriented(p))
        direct = general_direct_target_rows(p, q, r)
        full: List[List[Fraction]] = []
        phases = ((ONE, ONE, ONE), (IMAGINARY_UNIT, ONE, ONE))
        for a, b, c in product(
            transverse_basis(p), transverse_basis(q), transverse_basis(r)
        ):
            for phase in phases:
                modes = exact_triad_modes(p, q, r, a, b, c, phase)
                row = general_invariant_row(modes, representatives)[start : start + 8]
                if any(row):
                    full.append(row)
        assert direct == full
        comparisons += len(direct)
    return comparisons


def check_local_ranks(box: int = 1) -> tuple[int, int, int]:
    vectors = set(nonzero_vectors(box))
    unequal = equal = checked = 0
    for p in sorted(vectors):
        for q in sorted(vectors):
            r = neg(add(p, q))
            if r not in vectors or cross(p, q) == (0, 0, 0):
                continue
            rank = exact_rank(general_direct_target_rows(p, q, r))
            if norm2(q) != norm2(r):
                assert rank == 8
                unequal += 1
            else:
                assert rank == 4
                equal += 1
            checked += 1
    return checked, unequal, equal


def check_propagation_ranks() -> tuple[int, int]:
    # Import lazily to keep the coefficient generator independent of the
    # sparse-certificate module at import time.
    from verify_sparse_certificate import propagation_order

    ranked = replayed = 0
    for box in (2, 3, 4, 10):
        _representatives, steps = propagation_order(box)
        for _target, p, q, r in steps:
            assert norm2(q) != norm2(r)
            assert cross(q, r) != (0, 0, 0)
            if box <= 4:
                assert exact_rank(general_direct_target_rows(p, q, r)) == 8
                ranked += 1
            replayed += 1
    return ranked, replayed


def main() -> None:
    restriction_checks = check_hermitian_restriction()
    convolution_checks = check_full_convolution()
    direct_checks = check_direct_target_formula()
    checked, unequal, equal = check_local_ranks()
    ranked_steps, replayed_steps = check_propagation_ranks()
    (
        rank,
        dimension,
        equations,
        modular_ranks,
        selected_indices,
        pivot_columns,
        minor_determinants,
    ) = analyze_seed()
    assert rank == dimension - 2 == 54
    assert modular_ranks == (rank, rank)
    print(
        "Hermitian restriction and direct target formula: PASS "
        f"({restriction_checks} restricted-row, {convolution_checks} independent "
        f"convolution, and {direct_checks} target-row comparisons)"
    )
    print(
        "General local propagation ranks: PASS "
        f"({checked} signed triads; {unequal} rank eight, {equal} rank four)"
    )
    print(
        "Global propagation route: PASS "
        f"({ranked_steps} target blocks checked at rank eight; "
        f"{replayed_steps} steps replayed through radius ten)"
    )
    print(
        f"seven-mode general seed: {dimension} variables, {equations} "
        "nonzero equations, "
        f"rational rank {rank}, modular ranks {modular_ranks}, "
        f"nullity {dimension - rank}"
    )
    print(f"selected independent row indices: {selected_indices}")
    print(f"nonzero minor columns: {pivot_columns}")
    print(f"minor determinants modulo the two primes: {minor_determinants}")


if __name__ == "__main__":
    main()
