import FourierMultiplierRigidity.AnisotropicCorollary
import FourierMultiplierRigidity.TheoremAZero
import FourierMultiplierRigidity.TheoremD
import FourierMultiplierRigidity.FiniteCertificateOptimality
import FourierMultiplierRigidity.LocalSpectra
import FourierMultiplierRigidity.PhysicalSpaceCorollaryC
import FourierMultiplierRigidity.PhysicalSpaceIntegral
import FourierMultiplierRigidity.SmoothExtension
import FourierMultiplierRigidity.CertificateStability
import FourierMultiplierRigidity.SolenoidalSeedBridge

-- Human-readable trust report. Compilation errors are fatal; the separate
-- source check rejects admitted proofs. native_decide is an explicit trust
-- boundary, not claimed to be kernel reduction.
#print axioms FourierMultiplierRigidity.theoremA
#print axioms FourierMultiplierRigidity.corollaryB
#print axioms FourierMultiplierRigidity.theoremD_propagation
#print axioms FourierMultiplierRigidity.theoremD_finite_optimality
#print axioms FourierMultiplierRigidity.complexSolenoidal_ordered_count
#print axioms FourierMultiplierRigidity.hermitianSolenoidal_ordered_count
#print axioms FourierMultiplierRigidity.unrestrictedOutput_ordered_count
#print axioms FourierMultiplierRigidity.SolenoidalSeedCertificate.booleanSeedMatrixR_rank
#print axioms FourierMultiplierRigidity.SolenoidalSeedCertificate.booleanSeedMatrixR_nullity
#print axioms FourierMultiplierRigidity.FiniteCertificate.scalar_certificate_optimality
#print axioms FourierMultiplierRigidity.FiniteCertificate.complexSolenoidal_minimal
#print axioms FourierMultiplierRigidity.FiniteCertificate.hermitianSolenoidal_minimal
#print axioms FourierMultiplierRigidity.FiniteCertificate.unrestrictedOutput_minimal
#print axioms FourierMultiplierRigidity.LocalSpectra.rawMatrix_gram
#print axioms FourierMultiplierRigidity.LocalSpectra.projectedMatrix_gram
#print axioms FourierMultiplierRigidity.LocalSpectra.rawRecipient_frame_table
#print axioms FourierMultiplierRigidity.LocalSpectra.leray_crossRotate_difference
#print axioms FourierMultiplierRigidity.LocalSpectra.projectedObservation_gram
#print axioms FourierMultiplierRigidity.LocalSpectra.hermitian_observation_lower_bound
#print axioms FourierMultiplierRigidity.LocalSpectra.projection_defect_factor_sq
#print axioms FourierMultiplierRigidity.LocalSpectra.axis_route_sharp_bounds
#print axioms FourierMultiplierRigidity.LocalSpectra.completion_spectrum
#print axioms FourierMultiplierRigidity.LocalSpectra.completion_tangent_lower_bound
#print axioms FourierMultiplierRigidity.LocalSpectra.general_route_bounds
#print axioms FourierMultiplierRigidity.LocalSpectra.general_route_sharp_condition
#print axioms FourierMultiplierRigidity.LocalSpectra.axis_spectrum
#print axioms FourierMultiplierRigidity.LocalSpectra.general_route_bounds_two
#print axioms FourierMultiplierRigidity.LocalSpectra.general_route_sharp_condition_two
#print axioms FourierMultiplierRigidity.LocalSpectra.bootstrap_route_bounds
#print axioms FourierMultiplierRigidity.LocalSpectra.badFamily_spectrum
#print axioms FourierMultiplierRigidity.LocalSpectra.badFamily_condition
#print axioms FourierMultiplierRigidity.LocalSpectra.global_stability_from_least_singular_value
#print axioms FourierMultiplierRigidity.LocalSpectra.exists_least_singular_value
#print axioms FourierMultiplierRigidity.LocalSpectra.exists_stability_constant
#print axioms FourierMultiplierRigidity.SolenoidalSeedCertificate.booleanSeed_exists_stability_constant
#print axioms FourierMultiplierRigidity.SolenoidalSeedBridge.booleanSeedMatrix_rows_are_physical
#print axioms FourierMultiplierRigidity.SolenoidalSeedBridge.booleanSeedMatrixTypedZ_physical
#print axioms FourierMultiplierRigidity.SolenoidalSeedBridge.dot_symbol_expansion
#print axioms FourierMultiplierRigidity.SolenoidalSeedBridge.dot_symbol_hermitian
#print axioms FourierMultiplierRigidity.SolenoidalSeedBridge.dot_symbol_hermitian_neg
#print axioms FourierMultiplierRigidity.SolenoidalSeedBridge.triple_column_sum
#print axioms FourierMultiplierRigidity.SolenoidalSeedBridge.triple_column_sum_neg
#print axioms FourierMultiplierRigidity.SolenoidalSeedBridge.testPairing_eq_brackets
#print axioms FourierMultiplierRigidity.SolenoidalSeedBridge.rowPairing_zero
#print axioms FourierMultiplierRigidity.LocalSpectra.global_stability_mod_kernel
#print axioms FourierMultiplierRigidity.theoremAZero
#print axioms FourierMultiplierRigidity.theoremAZero_exact
#print axioms FourierMultiplierRigidity.zeroBlock_eq_complexification
#print axioms FourierMultiplierRigidity.replaceZeroBlock_universalAllModeCancellation_iff
#print axioms FourierMultiplierRigidity.StrainVorticity.corollaryC
#print axioms FourierMultiplierRigidity.StrainVorticity.corollaryC_solenoidal
#print axioms FourierMultiplierRigidity.StrainVorticity.physicalSVCubicForm_eq_svCubicForm
#print axioms FourierMultiplierRigidity.StrainVorticity.finiteTorusIntegral_physicalSVFourierSeries
#print axioms FourierMultiplierRigidity.StrainVorticity.corollaryC_finiteTorusIntegral
#print axioms FourierMultiplierRigidity.StrainVorticity.corollaryC_physical
#print axioms FourierMultiplierRigidity.StrainVorticity.corollaryC_physical_solenoidal
#print axioms FourierMultiplierRigidity.Torus.integral_expTerm
#print axioms FourierMultiplierRigidity.Torus.torusMean_char
#print axioms FourierMultiplierRigidity.Torus.torusMean_tripleSum
#print axioms FourierMultiplierRigidity.StrainVorticity.partialDeriv_fourierValue
#print axioms FourierMultiplierRigidity.StrainVorticity.physicalCurl_velocity
#print axioms FourierMultiplierRigidity.StrainVorticity.torusMean_strainVorticityDensity
#print axioms FourierMultiplierRigidity.StrainVorticity.torusMean_strainVorticity_eq_neg_transport
#print axioms FourierMultiplierRigidity.StrainVorticity.corollaryC_torusIntegral
#print axioms FourierMultiplierRigidity.StrainVorticity.corollaryC_torusIntegral_solenoidal
#print axioms FourierMultiplierRigidity.Smooth.summable_svAtom
#print axioms FourierMultiplierRigidity.Smooth.smoothSVForm_ofTrig
#print axioms FourierMultiplierRigidity.Smooth.tendsto_torusMean_truncate
#print axioms FourierMultiplierRigidity.Smooth.shearField_coeff_ne_trig
#print axioms FourierMultiplierRigidity.Smooth.corollaryC_smooth
#print axioms FourierMultiplierRigidity.Smooth.corollaryC_smooth_solenoidal
#print axioms FourierMultiplierRigidity.StrainVorticity.anisotropicOperator_eq_symbol
#print axioms FourierMultiplierRigidity.StrainVorticity.anisotropicOperator_cancellation
